video_root: '/cfs/cfs-rmuhzak3/lukenxu/dataset/value/videos/tvc/frames/frames_hq/'
ann_root: 'annotation/tvc'
# ann_root: 'annotation/tvc_private'
coco_gt_root: 'annotation/tvc'

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'
# pretrained: '/cfs/cfs-rmuhzak3/jarvicliu/blip_weight/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
pretrained: '/cfs/cfs-rmuhzak3/jarvicliu/blip_weight/model_base_caption_capfilt_large.pth'
# pretrained: '/cfs/cfs-rmuhzak3/jarvicliu/BLIP-main/output/Caption_tvc/checkpoint_best.pth'
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-5

# pretrained: '/cfs/cfs-rmuhzak3/jarvicliu/BLIP-main/output/Caption_tvc_vit16/checkpoint_best.pth'
# # pretrained: '/cfs/cfs-rmuhzak3/jarvicliu/blip_weight/model_large_caption.pth'
# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 6
# init_lr: 2e-6

image_size: 224
num_frm: 8

# generation configs
max_length: 32
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 20

