video_root: '[path_to_frames]'
ann_root: 'annotation/msrvtt'
coco_gt_root: 'annotation/msrvtt'

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
pretrained: ''
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-5

# pretrained: ''
# vit: 'large'
# vit_grad_ckpt: False
# vit_ckpt_layer: 0
# batch_size: 8
# init_lr: 1e-5

image_size: 224
num_frm: 8

# generation configs
max_length: 32
min_length: 5
num_beams: 5
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

